### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by clrh** [gabitoju/pymondrian#1]
Hi,

I am begining work with olap cubes and Saiku. I am happy to see your repository. I tried some others libs and didn't find what I was looking for. So thank you, I will give it a try in a true "context". 

* Do you plan to export one day Mondrian 4 ? I am not really fluent in python but maybe it is not hard to do a lot for a contributor, I will see.
* Which open source tools do you use with your cubes ?
* How do you validate your schema regarding the database structure ? (be sure that this column exists really in database for example and logical inside)

Regards.

**Comment by gabitoju** [comment]
Hello,

I'm glad you found this repo, it's been a long time since I commit something to it so you are very welcome to fork it and push to it :)

So, asking you questions:

- I think I can find same free time and change the schema to Mondrian 4. It shouldn't be that difficult (I guess :D)
- Beside Pentaho and Saiku it self I use Python a lot and some times PSPP.
- Right now there's no validation, at least for this project. It can generate its own DDBB schema from the Mondrian schema. For real life, scripts, pencil and paper.

Regards.

**Comment by clrh** [comment]
Thanks :)
